### ISSUE TITLE
Hosted service MontereyDistrictBoundaries/FeatureServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#1050]
The hosted service "District Boundaries" item exists f5bfbaca4c744df2b30479838de43afb but does not have an associated service definition portal item. Without the service definition item the service won't be published during Ops Server publishing.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, are supported by the ops server config publishing scripts.

Service will need to be republished so that a service definition item is uploaded to the portal.

**Comment by conklinbd** [comment]
Based on the lack of activity on this item. I am going to delete the item at 1100 today. If you think this is in error please respond by then.  Items like this cause us problems in QA/QC and have the potential to cause other problems as individuals reuse this content in their demo's/presentations.

**Comment by elinz** [comment]
Currently this feature service is being referenced in the following resources:
- Web Map, e2b7c18d24c340189af3b055b96b5238, "SustainmentReportingWebMap2", Aidan
- Web Map, b83cf730926943bdab17b0b91e9d6d98 , "Monterey Region (Incident Analysis)", DemoMilitary
- Web Map, b6de6ccb3495416f87ba747fa6ef61fb, "Incident Analysis - WebMap", Lyle
- Web Map, 8261b3fbc6b24939b63994061c55c9cc, "Operational Boundaries", Natalie F.

**Comment by conklinbd** [comment]
Based on the amount of dependent items, I am going to create a new hosted service by exporting the FGDB for this service and publishing from ArcMap.

**Comment by conklinbd** [comment]
I have published a new item and released it to the Demo Intel user.
/ags/rest/services/Hosted/DistrictBoundaries/FeatureServer/0

id:d997a2316ea940b8b3020cd099d06b4b

I will update the release web map to use this item.

**Comment by conklinbd** [comment]
I fixed the released web map and the one owned by Natalie F just in case it was about to be released. 
@elinz back to you to verify.

**Comment by elinz** [comment]
@conklinbd Web map b83cf730926943bdab17b0b91e9d6d98 is still broken as it still references old service Hosted/MontereyDistrictBoundaries/FeatureServer. New service is Hosted/DistrictBoundaries/FeatureServer. Back to you.

**Comment by conklinbd** [comment]
I updated b83cf730926943bdab17b0b91e9d6d98 again. It looks like it is correctly saved without the old layer. 
Back to @elinz to verify.

**Comment by elinz** [comment]
Verified that web maps b83cf730926943bdab17b0b91e9d6d98 and 8261b3fbc6b24939b63994061c55c9cc now reference the service Hosted/MontereyDistrictBoundaries/FeatureServer. Closing issue.
