### ISSUE TITLE
Hosted service LanguagesInUkraineByOblastTiles/MapServer does not have a service definition item

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#881]
The hosted service "Languages in Ukraine by Oblast (Tile Service)" item exists 348c793923c94499a9a9d4cce4d4224d but does not have an associated service definition portal item. Without the service definition item the service won't be published to any user conference machines.

NOTE: Only hosted services published from ArcGIS Desktop or ArcGIS Pro, which upload a service definition item to portal, will be published to the UC servers.

Owned by Craig C. Either he doesn't have a GitHub account or his account does not have access to the Esri org.

**Comment by jrweakland** [comment]
@CraigCleveland

**Comment by CraigCleveland** [comment]
@elinz @jrweakland The ability to publish hosted tile services from ArcGIS Desktop was not possible during the publishing process.  Both myself and Avi could not remedy the issue when we were looking into it.  To that end I published the hosted feature services and generated the tiles from there.  I'll re-work the web maps to just consume the feature services and deal with the performance issues...

**Comment by elinz** [comment]
@CraigCleveland FYI: Re-ran report and the Hosted\LanguagesInUkraineByOblastTiles/MapServer item still exists. Without service definition portal item, the service won't be published during stand-up of Ops Server. Options are to republish the hosted service so service definition item is uploaded to portal or delete this hosted service. Thanks.

**Comment by CraigCleveland** [comment]
@elinz given that the performance of the feature services in and of themselves (i.e. without tile services) was not that bad, I plan to leave the map and apps the way they are.  Just not worth the additional busy work.  If I unshare the tile services that were generated from the feature services is that enough for you?  Or do you need me to delete them outright?

**Comment by elinz** [comment]
@CraigCleveland Please delete the un-needed hosted LanguagesInUkraineByOblastTiles map service. Thanks.

**Comment by CraigCleveland** [comment]
@elinz - deleted.

**Comment by elinz** [comment]
@CraigCleveland The hosted service LanguagesInUkraineByOblastTiles.MapServer still exists (portal item doesn't exist). I can delete this for you, just let me know.

**Comment by CraigCleveland** [comment]
@elinz - deleted.  Not sure how it got orphaned, but either way it's taken care of now.

**Comment by nfeuerstein** [comment]
Confirmed it was deleted.
