### ISSUE TITLE
Service Definition item (liberiaborders) exists without an associated hosted service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#888]
Hosted service liberiaborders/FeatureServer no longer exists, but associated service definition item exists; please delete the following item; otherwise the hosted service will be published to the UC machines:
id: 8a1a5703c67040c5b9a13c57e7aafa4e  owner: sara7600@AVWORLD    type: Service Definition

**Comment by conklinbd** [comment]
This was fixed while I was releasing content.

**Comment by elinz** [comment]
@conklinbd Reopening as the service definition item 8a1a5703c67040c5b9a13c57e7aafa4e still exists. I will delete this item.

**Comment by elinz** [comment]
@conklinbd Delete the service definition item 8a1a5703c67040c5b9a13c57e7aafa4e. Closing issue.
