### ISSUE TITLE
Service Definition item (ebolahealthcarefacilities) exists without an associated hosted service

### ISSUE THREAD

**Issue by elinz** [Esri/ops-server-config#889]
Hosted service ebolahealthcarefacilities/FeatureServer no longer exists, but associated service definition item exists; please delete the following item; otherwise the hosted service will be published to the UC machines:

id: 81a7f02a6bd243f3bc33497cd1eaec66  owner: sara7600@AVWORLD    type: Service Definition

**Comment by conklinbd** [comment]
This was fixed while I was releasing Intel content.

**Comment by elinz** [comment]
@conklinbd Reopening as service definition item 81a7f02a6bd243f3bc33497cd1eaec66 still exists. I will go ahead and delete.

**Comment by elinz** [comment]
@conklinbd I delete the service definition item. Closing issue.
